# Generated by Django 6.0.6 on 2026-06-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comercio',
            name='fecha_fin_destacado',
            field=models.DateField(blank=True, help_text='Si se deja vacío, el destacado no vence solo.', null=True),
        ),
    ]
