# Generated by Django 6.0.6 on 2026-07-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0002_comercio_destacado_comercio_fecha_fin_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='logo',
            field=models.ImageField(blank=True, help_text='Subir un archivo acá lo sube a R2 y actualiza logo_url automáticamente.', null=True, upload_to='comercios/logos/'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='logo_url',
            field=models.URLField(blank=True, help_text="Se recalcula solo a partir de 'logo' al guardar -- no editar a mano.", null=True),
        ),
    ]
