# Generated by Django 6.0.6 on 2026-07-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nombre normalizado (sin tildes/mayúsculas) usado para emparejar el mismo producto entre comercios. Se calcula solo, no editar a mano.', max_length=200),
        ),
    ]
