# Generated by Django 6.0.6 on 2026-07-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_backfill_nombre_normalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_normalizada',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Presentación (volumen o peso) extraída del nombre en unidad canónica, ej. 'volumen:1000' o 'peso:2000'. Se calcula solo.", max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca_normalizada',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Marca conocida detectada en el nombre (ver MARCAS_CONOCIDAS), usada junto a cantidad_normalizada como criterio de matching cuando el nombre completo no coincide entre comercios. Se calcula solo.', max_length=50),
        ),
    ]
