# Generated by Django 6.0.6 on 2026-07-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='conteo_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Cuántas unidades trae el empaque (de patrones tipo 'x24', 'C/50'), extraída del nombre. Se calcula solo.", max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='dosis_normalizada',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Dosis por unidad (mg/gr, normalizada a mg) extraída del nombre, ej. '500' o '37.5+325' si es combinada. Usada junto a conteo_normalizado para el matching de farmacia. Se calcula solo.", max_length=50),
        ),
    ]
